ARG ROS_DISTRO=humble
ARG PREFIX=

FROM husarnet/ros:${PREFIX}${ROS_DISTRO}-ros-core

RUN apt update && apt install -y \
      ros-${ROS_DISTRO}-camera-calibration-parsers \
      ros-${ROS_DISTRO}-camera-info-manager \
      ros-${ROS_DISTRO}-image-proc \
      ros-${ROS_DISTRO}-camera-calibration
