services:

  camera:
    build:
      context: ../
      dockerfile: Dockerfile
    devices:
      - /dev/video0:/dev/video0
    # runtime: nvidia
    volumes:
      - ./logitech_webcam_c930e.yaml:/root/.ros/camera_info/default_cam.yaml
      - ./camera_launch.py:/camera_launch.py
      - ./params/camera_params.yaml:/camera_params.yaml
      - ./cam.launch.py:/ros2_ws/install/foxglove_compressed_video_transport/share/foxglove_compressed_video_transport/launch/cam.launch.py
      # - ./params/ffmpeg_params.yaml:/ffmpeg_params.yaml

    # command: >
    #   ros2 run v4l2_camera v4l2_camera_node
    #     --ros-args 
    #     -p video_device:=/dev/video0
    #     -p pixel_format:=YUYV
    #     -p output_encoding:=yuv422_yuy2
    #     -p image_size:="[640,480]" 
    #     -p camera_frame_id:=camera_optical_link
    # command: tail -f /dev/null
    # command: ros2 run usb_cam usb_cam_node_exe
    # command: ros2 launch /camera_launch.py
    # command: >
    #   ros2 run usb_cam usb_cam_node_exe
    #     --ros-args
    #     -p params_file:=/camera_params.yaml
    #     -p video_device:=/dev/video0
    command: ros2 launch foxglove_compressed_video_transport cam.launch.py
    # command: >
    #   ros2 run usb_cam usb_cam_node_exe
    #     --ros-args
    #     -p params_file:=/camera_params.yaml
    #     -p video_device:=/dev/video0

  foxglove-bridge:
    build:
      context: .
      dockerfile: Dockerfile.foxglove-bridge
    ports:
      - 8766:8766
    command: ros2 launch foxglove_bridge foxglove_bridge_launch.xml port:=8766

  # rviz:
  #   image: husarion/rviz2:humble-11.2.6
  #   volumes:
  #     - /tmp/.X11-unix:/tmp/.X11-unix:rw
  #     - ./default.rviz:/root/.rviz2/default.rviz
  #   environment:
  #     - DISPLAY=${DISPLAY:?err}
  #     - LIBGL_ALWAYS_SOFTWARE=1

