FROM ros:humble-ros-core

RUN apt update && apt upgrade -y && apt install -y \
        ros-${ROS_DISTRO}-foxglove-bridge \
        ffmpeg \
        libpulse-dev \
        libblas3 \
        libjpeg-turbo8-dev \
        ros-${ROS_DISTRO}-cv-bridge \
        ros-${ROS_DISTRO}-image-transport \
        ros-${ROS_DISTRO}-image-transport-plugins \
        ros-${ROS_DISTRO}-ffmpeg-image-transport \
        ros-${ROS_DISTRO}-foxglove-msgs

