/**:
    ros__parameters:
      framerate: 30.0
      io_method: "mmap"
      pixel_format: "mjpeg2rgb"  # see usb_cam/supported_formats for list of supported formats
      av_device_format: "YUV422P"
      # image_width: 640
      # image_height: 480
      image_width: 1280
      image_height: 720
      camera_name: default_camera
      camera_info_url: "package://usb_cam/config/camera_info.yaml"
      # camera_info_url: "file:///var/snap/husarion-camera/common/camera_info_default.yaml"
      brightness: -1
      contrast: -1
      saturation: -1
      sharpness: -1
      gain: -1
      auto_white_balance: true
      white_balance: 4000
      autoexposure: true
      exposure: 100
      autofocus: false
      focus: -1
      # foxglove:
      #   enconding: "libx264"
      #   preset: "ultrafast"
      #   tune: "zerolatency"
      image_raw:
        foxglove:
          encoding: "libx264"
          profile: "main"
          preset: "ultrafast"
          tune: "zerolatency"