---
/**:
  ros__parameters:
    ffmpeg_image_transport:

      # find the list of available encoders by running `ffmpeg -encoders`
      encoding: libx264
      # encoding: h264_nvenc
      
      # find the list of available presets by running `ffmpeg -h encoder=libx264`
      preset: ultrafast
      # preset: veryslow
      tune: zerolatency
      # gop_size: 100
      # profile: high444